name: SQL Database Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: "event_management"
  SQLCL_PATH: "/opt/homebrew/Caskroom/sqlcl/25.1.1.113.2054/sqlcl/bin/sql"

jobs:
  # Job for pull request validation - runs on PR creation/update to main
  validate-pr:
    name: SQL PR Validation
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Verify SQL Project
        run: |
          # Create SQL script for verification
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.DEV_CONNECTION_STRING }}" > verify.sql
          echo "project verify -verbose" >> verify.sql
          ${SQLCL_PATH} @verify.sql
      
      - name: Check for SQL Errors
        run: |
          if grep -r "ORA-" ./dist/releases/next/changes; then
            echo "SQL errors found in staged changes"
            exit 1
          fi
          echo "No SQL errors found in staged changes"
          
  # Jobs for push to main (after PR merge) - create release and deploy to environments
  release-artifact:
    name: SQL Release Creation
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.release_version.outputs.version }}
      artifact_name: ${{ steps.release_version.outputs.artifact_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Create Release Version
        id: release_version
        run: |
          # Generate version based on semantic versioning with date
          MAJOR_VERSION=1.0
          RELEASE_SUFFIX=$(date +%Y%m%d)-${{ github.run_number }}
          VERSION="$MAJOR_VERSION"
          ARTIFACT_VERSION="$MAJOR_VERSION-$RELEASE_SUFFIX"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "artifact_name=${{ env.PROJECT_NAME }}-$ARTIFACT_VERSION.zip" >> $GITHUB_OUTPUT
          echo "artifact_version=$ARTIFACT_VERSION" >> $GITHUB_OUTPUT
          echo "Created release version: $VERSION (Artifact: $ARTIFACT_VERSION)"
      
      - name: Create Project Release
        run: |
          # Create SQL script for release creation
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.DEV_CONNECTION_STRING }}" > release.sql
          echo "project release -version ${{ steps.release_version.outputs.version }} -verbose" >> release.sql
          ${SQLCL_PATH} @release.sql
      
      - name: Generate Artifact
        run: |
          # Create SQL script for artifact generation
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.DEV_CONNECTION_STRING }}" > artifact.sql
          echo "project gen-artifact -version ${{ steps.release_version.outputs.artifact_version }}" >> artifact.sql
          ${SQLCL_PATH} @artifact.sql
      
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Version ${{ steps.release_version.outputs.version }}"
          git push
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sql-artifact
          path: dist/artifacts/${{ steps.release_version.outputs.artifact_name }}
          retention-days: 30
  
  deploy-test:
    name: SQL Deploy to TEST
    needs: release-artifact
    runs-on: self-hosted
    environment:
      name: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Release Artifact
        uses: actions/download-artifact@v3
        with:
          name: sql-artifact
          path: ./artifacts
      
      - name: Deploy to TEST
        run: |
          # Create SQL script for TEST deployment
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.TEST_CONNECTION_STRING }}" > deploy.sql
          echo "project deploy -file ./artifacts/${{ needs.release-artifact.outputs.artifact_name }} -verbose" >> deploy.sql
          
          # Execute SQLcl to deploy to TEST
          ${SQLCL_PATH} @deploy.sql
      
      - name: Run Validation Tests
        run: |
          # Create SQL script for validation tests
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.TEST_CONNECTION_STRING }}" > tests.sql
          echo "select table_name from all_tables where owner='EM';" >> tests.sql
          echo "select count(*) from all_constraints where owner='EM';" >> tests.sql
          
          # Execute SQLcl to validate deployment
          ${SQLCL_PATH} @tests.sql
  
  deploy-uat:
    name: SQL Deploy to UAT
    needs: [release-artifact, deploy-test]
    runs-on: self-hosted
    environment:
      name: uat
      # Environment protection rule - requires approval for UAT
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Release Artifact
        uses: actions/download-artifact@v3
        with:
          name: sql-artifact
          path: ./artifacts
      
      - name: Deploy to UAT
        run: |
          # Create SQL script for UAT deployment
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.UAT_CONNECTION_STRING }}" > deploy.sql
          echo "project deploy -file ./artifacts/${{ needs.release-artifact.outputs.artifact_name }} -verbose" >> deploy.sql
          
          # Execute SQLcl to deploy to UAT
          ${SQLCL_PATH} @deploy.sql

  deploy-prod:
    name: SQL Deploy to PROD
    needs: [release-artifact, deploy-test, deploy-uat]
    runs-on: self-hosted
    environment:
      name: prod
      # Environment protection rule - requires approval for PROD
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Release Artifact
        uses: actions/download-artifact@v3
        with:
          name: sql-artifact
          path: ./artifacts
      
      - name: Deploy to PROD
        run: |
          # Create SQL script for PROD deployment
          echo "connect \"SVC_CICD\"/\"${{ secrets.CICD_PASSWORD }}\"@${{ secrets.PROD_CONNECTION_STRING }}" > deploy.sql
          echo "project deploy -file ./artifacts/${{ needs.release-artifact.outputs.artifact_name }} -verbose" >> deploy.sql
          
          # Execute SQLcl to deploy to PROD
          ${SQLCL_PATH} @deploy.sql

